src/api/mod.rs

Makes it easier to create a BDAddr/UUID by allowing parsing them from the same format as they are displayed

Allow parsing UUID and BDAddr from str

---

.gitignore
examples/discover_adapters_peripherals.rs

Hi
I've added one of my research code. It can 
- discover local BLE adapter
- discover found peripheral device(s)
- connect it 
- dump characteristics
- disconnect from BLE
Code is tested on Linux as primary OS.

Added adpater discovery and ble peripheral discovery example

---

README.md
examples/event_driven_discovery.rs
src/api/mod.rs

Added `on_event` example. Related to https://github.com/deviceplug/btleplug/issues/40
My VSCode also removed some trailing spaces, I hope you don't mind.
Please squash upon merging. Thanks.

Added `on_event` example

---

src/api/mod.rs

This PR is to broaden accepted values for `UUID::from_str()`.  
Usually we encounter UUID like this: `2f029dc0-98ff-40e4-aa1e-628135afe1ed`. To make it acceptable by `UUID::from_str()` we'd have to convert it to `2F:02:9D:C0:98:FF:40:E4:AA:1E:62:81:35:AF:E1:ED`. This change will accept both inputs.  
The conversion back `to_string()` will still produce `2F:02:9D:C0:98:FF:40:E4:AA:1E:62:81:35:AF:E1:ED`.

Simplify accepted inputs to UUID::from_str()

---

src/api/mod.rs
src/bluez/adapter/peripheral.rs
src/corebluetooth/peripheral.rs
src/winrtble/peripheral.rs

It was either unimplemented or did exactly the same as discover_characteristics.

Remove discover_characteristics_in_range.

---

src/corebluetooth/central_delegate.rs
src/corebluetooth/internal.rs
src/winrtble/ble/characteristic.rs
src/winrtble/ble/device.rs

Does what it says in the title. :3

Log messages de-escalation

---

build/default.yml
src/api/adapter_manager.rs
src/api/mod.rs
src/bluez/adapter/mod.rs
src/bluez/adapter/peripheral.rs
src/bluez/mod.rs
src/common/util.rs
src/corebluetooth/adapter.rs
src/corebluetooth/internal.rs
src/winrtble/adapter.rs
src/winrtble/ble/device.rs
src/winrtble/peripheral.rs

Fix the check itself, and then format and fix a bunch of clippy errors and warnings.

Make style linting check pass

---

README.md

Add docs.rs badge with link to latest published docs.

---

Cargo.toml
build.rs
src/winrtble/adapter.rs
src/winrtble/ble/characteristic.rs
src/winrtble/ble/device.rs
src/winrtble/ble/watcher.rs
src/winrtble/manager.rs
src/winrtble/peripheral.rs
src/winrtble/utils.rs

Rename module names and method names in windows crate from snake_case to CamelCase.

Update to windows 0.7.0

---

src/winrtble/ble/characteristic.rs

Noticed this issue during development of an embedded system. 
This change will query the GATT characteristic properties for support of either notification or indication and will subscribe accordingly. Though this is a quick fix IMO, and it may be better to cache the properties, to save looking it up for each call to subscribe.

Windows: Support subscribing using either Notify or Indicate

---

README.md
examples/discover_adapters_peripherals.rs
examples/event_driven_discovery.rs
examples/lights.rs
src/corebluetooth/adapter.rs
src/corebluetooth/framework.rs
src/corebluetooth/internal.rs
src/winrtble/ble/characteristic.rs

Check Bluetooth authorisation status on macOS, and add note about permissions

---

examples/discover_adapters_peripherals.rs
examples/subscribe_notify_characteristic.rs

I worked on that missing and main example for a long time since sync api.
Rebease didn't succeed. New fork and new PR.

added subscribe notification characteristic example

---

CHANGELOG.md
Cargo.toml
src/corebluetooth/framework.rs
src/corebluetooth/internal.rs
src/corebluetooth/peripheral.rs

I tried to keep things minimal for my first PR.
I had to expose a new `CBPeripheralState` to get the correct state. 
Let me know if that works for you.

Wrote `is_connected` for CoreBluetooth

---

src/winrtble/peripheral.rs

_Note: this is based on https://github.com/deviceplug/btleplug/pull/183, so the first patch can be ignored here_
When I was looking at making changes in the winrtble backend I noticed that there were lots of separately boxed internal struct members and as far as I could see the only purpose for putting this state under `Arc<>`s was because a `Peripheral` is expected to implement Clone and so conceptually all this internal state can effectively be shared in case a Peripheral gets `clone()`d multiple times.
As is; each `Arc<>` is a separate heap allocation with a seperate ref count though and the derived implementation of `Clone` will necessarily have to increment each separate ref count when they could instead all be grouped together into a single heap allocation and `Clone` can be reduced …

Winrtble: aggregate share Peripheral state under one boxed Arc

---

Cargo.toml
src/bluez/adapter.rs
src/lib.rs

This should fix #165. Fixed some warnings while I was at it.

Update to latest version of bluez-async

---

src/bluez/adapter.rs
src/bluez/peripheral.rs

This should be a little more efficient.

Convert MacAddress to BDAddr directly without going via a String.

---

CHANGELOG.md
src/bluez/adapter.rs

bluez: Synthesise DeviceConnected events too.

---

src/winrtble/ble/device.rs
src/winrtble/peripheral.rs

This PR contains a device disconnect change for Windows as well as a workaround for some weird behaviour seen on characteristic discovery.

WinRT BLE improvements

---

LICENSE.md

Found this, uh, _autocomplete_ error in the license.

Fix buttplug error in the license.

---

src/droidplug/jni/objects.rs

Fixing https://github.com/deviceplug/btleplug/issues/296

Added rssi for droidplug

---

src/api/mod.rs

Implements Serialize and Deserialize traits for PeripheralProperties via derive.

Derive Serialize and Deserialize for PeripheralProperties

---

src/api/mod.rs
src/bluez/peripheral.rs
src/corebluetooth/peripheral.rs
src/droidplug/jni/objects.rs
src/winrtble/peripheral.rs

Issue: https://github.com/deviceplug/btleplug/issues/284
Map class property to read device type.

add class property

---

src/droidplug/adapter.rs
src/droidplug/java/src/main/java/com/nonpolynomial/btleplug/android/impl/Adapter.java
src/droidplug/java/src/main/java/com/nonpolynomial/btleplug/android/impl/ScanFilter.java
src/droidplug/jni/mod.rs
src/droidplug/jni/objects.rs

feat: implement scan filters for android

---

src/winrtble/adapter.rs
src/winrtble/ble/watcher.rs

feat: implement scan filter for windows

---

src/droidplug/peripheral.rs

Android future exception

---

src/api/mod.rs
src/bluez/peripheral.rs
src/corebluetooth/central_delegate.rs
src/corebluetooth/framework.rs
src/corebluetooth/internal.rs
src/corebluetooth/peripheral.rs
src/corebluetooth/utils/core_bluetooth.rs
src/droidplug/java/src/main/java/com/nonpolynomial/btleplug/android/impl/Peripheral.java
src/droidplug/jni/objects.rs
src/droidplug/peripheral.rs
src/winrtble/ble/characteristic.rs
src/winrtble/ble/descriptor.rs
src/winrtble/ble/device.rs
src/winrtble/ble/mod.rs
src/winrtble/peripheral.rs

Discovery of characteristics descriptors, implemented and tested for all platforms

Descriptors discovery

---

src/droidplug/java/src/main/java/com/nonpolynomial/btleplug/android/impl/Peripheral.java
src/droidplug/jni/mod.rs
src/droidplug/jni/objects.rs
src/droidplug/peripheral.rs
src/lib.rs

Bugfix 311

---

src/droidplug/java/src/main/java/com/nonpolynomial/btleplug/android/impl/Adapter.java

Correct an Android NPE
