- src/bluez/adapter/mod.rs
PS: I noticed that my previous PR was set to the `dev` branch and not `master`, not sure if that was correct, I've put this one against `dev` too but things might need to be merged to master
> set dev_id when creating bluez adapter from device info

- src/bluez/adapter/mod.rs
Had a strange issue where one of my devices never advertised its local name (but it did with noble for nodejs).  Appears that it only does so if the scan is active!
Documentation for the Central trait:
> Control whether to use active or passive scan mode to find BLE devices....Defaults to use active mode.
There's no control on this for Mac or Windows (the active fn is a noop), so no updates required for other platforms.
> For linux, default the scan to active, as this is what's in the docs.

- src/lib.rs
Small fix for comment that confused me for a second. The updated text is consistent with the rumble README quoted in this repo's README:
https://github.com/deviceplug/btleplug/blob/984e6cf363176927c008d8a5d26b01edac4517cf/README.md#rumble
> Correct comment regarding BlueZ sockets

- src/corebluetooth/adapter.rs
- src/corebluetooth/internal.rs
- src/corebluetooth/peripheral.rs
MacOS 10.15 (10.14?) somehow changed the process of peripheral discovering, we may not have the name when the first time a device is discovered, and the name comes with following `centralManager:didDiscover...` events.
> Correctly get peripheral local_name on macOS 10.15

- src/bluez/adapter/mod.rs
I looked into the code in order trying to understand how to use Bluez. 
This part stuck as it looked weird. Why should we use a mutable object for libc::write ?
Monkey patched it to use a const object
> Use const rather a mut object to write

- README.md
- src/corebluetooth/central_delegate.rs
- src/corebluetooth/framework.rs
- src/corebluetooth/internal.rs
- src/corebluetooth/peripheral.rs
As the title says. Plus, for debugging purposes, I had to get the message from the error objects that get passed by Core Bluetooth on failure. I thought this would be a nice addition to the code, so we get more context than just `error`.
Please note: I am a total Rust n00b, so there may be a lot of stuff in this PR that is not idiomatic Rust. Please bare with me. I am super interested in fixing that, though, so any comments are welcome.
I've tried to keep the current code style.
Oh, and one last thing: It would totally make sense to split this PR into two - one for adding read support, another for adding write with response. However, the BLE device I am trying to get working (a smart radiator valve) requires both to be in place before I know it's working, so I am unable to do the split …
> feat: Add write with response and read on Core Bluetooth

- examples/lights.rs
This is a very minor thing.
The change just communicates the error better when running the `lights` example without any lights available (which I imagine will be most people).
Before:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', examples/lights.rs:55:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
After:
```
thread 'main' panicked at 'No lights found', examples/lights.rs:55:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
> Improve error message for lights example.

- src/corebluetooth/adapter.rs
- src/corebluetooth/central_delegate.rs
- src/corebluetooth/internal.rs
- src/corebluetooth/peripheral.rs
Simple fix for failing macOS builds due to async_std changing the `async_std::sync` API to `async_std::channel`
> MacOS: Fix async_std breaking changes

- examples/lights.rs
- src/api/adapter_manager.rs
- src/api/mod.rs
- src/bluez/adapter/peripheral.rs
- src/corebluetooth/peripheral.rs
- src/winrtble/peripheral.rs
It's not very useful for clients to receive all manufacturer data concatenated together, when it has a well-defined structure.
This is a breaking change to the API.
> Expose manufacturer data as HashMap rather than concatenating it all

- src/api/mod.rs
- src/bluez/adapter/peripheral.rs
- src/corebluetooth/peripheral.rs
- src/winrtble/peripheral.rs
This removes `command_async`, `request_async`, `read_async` and `read_by_type_async`, which were not implemented on any platform. This is theoretically a breaking change, but any user of them is already broken because none of them actually did what they claimed to.
I've also removed the return value of `request`, because it seems to have originated from a misunderstanding of the GATT protocol. The device doesn't send a value back, only a confirmation that the write succeeded. On platforms where this was implemented it was just returning the same value which was written, which is not very useful.
We could consider going a step further and merging `request` and `command` into a single `write` method, as it is unlikely to matter to a user of the library whether it is really a write or a …
> Remove unimplemented methods and fix return type of request

- Cargo.toml
- src/api/adapter_manager.rs
- src/corebluetooth/adapter.rs
- src/corebluetooth/central_delegate.rs
- src/corebluetooth/internal.rs
- src/corebluetooth/manager.rs
- src/corebluetooth/mod.rs
- src/corebluetooth/peripheral.rs
- src/corebluetooth/utils.rs
This cleans up several things on Mac OS:
* Adds a `Debug` implementation for many types.
* Removes some unused code and fixes some other warnings.
* Sets local_name to `None` rather than `Some("nil")` for devices without a name.
* Either logs or returns errors in some cases where they were being ignored (and causing compile warnings).
Let me know if you'd prefer it to be split into smaller PRs.
> Clean up corebluetooth module

- README.md
- examples/lights.rs
- src/api/mod.rs
- src/bluez/adapter/peripheral.rs
- src/corebluetooth/internal.rs
- src/corebluetooth/peripheral.rs
- src/lib.rs
- src/winrtble/ble/characteristic.rs
- src/winrtble/peripheral.rs
This is hopefully easier to understand, and more similar to other GATT APIs.
It appears that the write types were backwards on Mac OS before, so this also fixes that.
I don't have a Windows machine to build on, so I haven't been able to implement this on Windows.
Fixes #111.
> Replace request and command with a single write method.

- src/corebluetooth/central_delegate.rs
- src/corebluetooth/internal.rs
- src/corebluetooth/utils.rs
This fixes a bug where 16-bit UUIDs were not being converted properly.
Fixes #119.
> Add helper function to convert CBUUID to Uuid.

- Cargo.toml
- src/api/adapter_manager.rs
- src/api/mod.rs
- src/bluez/adapter/mod.rs
- src/bluez/adapter/peripheral.rs
- src/bluez/manager/mod.rs
- src/corebluetooth/adapter.rs
- src/corebluetooth/central_delegate.rs
- src/corebluetooth/framework.rs
- src/corebluetooth/future.rs
- src/corebluetooth/internal.rs
- src/corebluetooth/peripheral.rs
- src/corebluetooth/utils.rs
- src/lib.rs
- src/winrtble/ble/characteristic.rs
- src/winrtble/ble/device.rs
This removes some unnecessary dependencies, moves some to only the platforms that actually require them, and removes 2015 edition style `extern crate` declarations in favour of using macros individually.
> Clean up dependencies

- src/api/mod.rs
Just a quick simple fix, I noticed the ordering was wrong in the Characteristic display function.
> Fix ordering of Characteristic display.

- src/corebluetooth/adapter.rs
- src/corebluetooth/central_delegate.rs
- src/corebluetooth/future.rs
- src/corebluetooth/internal.rs
- src/corebluetooth/peripheral.rs
This is multi producer single consumer whereas `async_std::channel` is multi producer multi consumer, so this change required some refactoring to stop cloning the receiver. I think the result is a bit cleaner too.
This is a step towards removing the `async_std` dependency and moving to Tokio.
The examples still seem to work fine, but it could do with some stress testing to make sure there aren't any concurrency bugs I've missed.
Helps with #45.
> Use futures::channel::mpsc instead of async_std::channel.

- examples/event_driven_discovery.rs
- src/api/mod.rs
- src/bluez/adapter/peripheral.rs
- src/corebluetooth/central_delegate.rs
- src/corebluetooth/framework.rs
- src/corebluetooth/internal.rs
- src/corebluetooth/peripheral.rs
- src/winrtble/mod.rs
- src/winrtble/peripheral.rs
- src/winrtble/utils.rs
Bluetooth advertisement may also contain Service Data (that is, Service UUIDs followed by arbitrary bytes) and advertised services. 
This Merge Request adds 
1. `service_data` and `services` to `btleplug::api::PeripheralPropties` 
2. `ManufacturerDataAdvertisement`, `ServiceDataAdvertisement` and `ServiceSAdvertisement` to `btleplug::api::CentralEvent`
3. Emits appropriate events from BlueZ, WinRT and Core Bluetooth
- WinRT requried some manual parsing as there isn't a direct API for Service Data
- Core Bluetooth didn't implement manufacturer data, so that was also added
> [Feature] Advertisement support for Service Data, Manufacturer Data and Services

- Cargo.toml
- src/api/mod.rs
To maintain a `serde` feature with the btleplug package, some package
renaming magic needed to happen. See
- https://blog.turbo.fish/cargo-features/
- https://github.com/serde-rs/serde/issues/1990
> Fix serde support for Uuid type

- src/api/mod.rs
- src/bluez/adapter/mod.rs
- src/corebluetooth/adapter.rs
- src/winrtble/adapter.rs
With both `Adapter` and `Peripheral` being platform specific, I can't see any situation where you would want to implement `Central` more than once for a single `Adapter` but with different `Peripheral`s.
By removing the generic parameter instead it makes the trait easier to work with in generics.
> move Peripheral from general parameter to associated type for Central

- examples/event_driven_discovery.rs
- src/api/mod.rs
- src/bluez/adapter/peripheral.rs
- src/corebluetooth/peripheral.rs
- src/winrtble/peripheral.rs
With the recent  #126, `CentralEvent::ManufacturerDataAdvertisement` and `CentralEvent::ServiceDataAdvertisement` were emitted for the individually paired _manufacturer data_ and _service data_ received. Not ideal when they often provided as a mapping. It also makes it slightly more difficult  when it's needed to emit more than one event, such as https://github.com/deviceplug/btleplug/pull/114#discussion_r588820284
> Fix emitting individual manufacturer data and service data

- Cargo.toml
- examples/discover_adapters_peripherals.rs
- examples/event_driven_discovery.rs
- examples/lights.rs
- src/bluez/adapter/mod.rs
- src/bluez/adapter/peripheral.rs
- src/bluez/manager/mod.rs
- src/corebluetooth/adapter.rs
- src/corebluetooth/peripheral.rs
- src/lib.rs
- src/platform.rs
- src/winrtble/adapter.rs
- src/winrtble/manager.rs
- src/winrtble/peripheral.rs
By re-exporting the platform specific `Manager` and `Adapter` saves the user of the api from doing so and should prevent most api users from "accidentally" making their code platform specific.
By type-aliasing `Adapter `as `ConnectedAdapter` for mac and windows, and adding a no-op `connect` the user doesn't have to care that only linux
has a difference between the two.
> unify api usage between platforms a bit

- Cargo.toml
- build/default.yml
the crate _serde_bytes_ is also added as it's needed for `Vec<u8>` and `Vec<Uuid>`
> Reintroduce `cargo check --all-features` and `cargo check --no-default-features`

- src/api/mod.rs
- src/lib.rs
A crate should not hide its own error types by stringifying them.
> Add variant for errors from uuid crate

- src/api/bdaddr.rs
- src/api/mod.rs
- src/corebluetooth/adapter.rs
- src/lib.rs
- src/winrtble/adapter.rs
- src/winrtble/ble/device.rs
- src/winrtble/utils.rs
This PR follows the discussion of #68.
At last I found some time to work on this. For now I refactored `BDAddr` as a show case what I intend to do. If the implementation is approved I'll start working on `UUID`. Of course I'll include the changed suggested in #80 as well.
Initially, I wanted to write the parsers with `nom` but I recognized that there is a bunch of `nom v4` code in the crate so I settled for a 'hand-crafted' version. Another solution would be to use `regex` but I didn't wanted to pull in another dependency without asking.
> Refactor BDAddr

- Cargo.toml
- src/winrtble/ble/characteristic.rs
- src/winrtble/ble/device.rs
- src/winrtble/manager.rs
- src/winrtble/mod.rs
This fixes `windows::Error` to be `Send + Sync`, which allows the workarounds which were added for the async change before to be reverted.
> Update to windows 0.6.0

- src/winrtble/ble/characteristic.rs
- src/winrtble/peripheral.rs
> Fix Peripheral::characteristics() on Windows

- CHANGELOG.md
- Cargo.toml
- src/winrtble/ble/characteristic.rs
All of these methods now return std::Error, meaning we can just use the ? operator instead of panicking to pass the error up to the user.
Aiming this PR at master since async already came into dev. On r+, I'll update version/changelog and release 0.7.2, then will handle the dev branch rebase myself so we stay linear there.
> chore: Remove unwraps in UWP characteristics

- Cargo.toml
- src/api/bdaddr.rs
- src/api/mod.rs
- src/lib.rs
- src/serde.rs
- src/winrtble/ble/characteristic.rs
- src/winrtble/peripheral.rs
Like suggested in #68 this PR adds options to de-/serialize `BDAddr` in different formats.
If this get merged I could do a similar solution for the UUIDs.
> Add custom de-/serialization for BDAddr

- build.rs
- src/winrtble/ble/characteristic.rs
Closes #155 
For some reason `BluetoothCacheMode(1)` is the no caching mode and `BluetoothCacheMode(0)` uses the cache. See [docs](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothcachemode?view=winrt-19041#fields)
Using `BluetoothCacheMode::Uncached` did not work for me. Maybe this is not really an enum? My IDE was also not very helpful regarding these windows bindings.
> Force  to read from GattCharacteristic from device instead of cache

- .github/workflows/rust.yml
This is necessary to get proper coverage diffs on PRs to dev.
> Run jobs on push to dev too

- src/winrtble/peripheral.rs
Update `Peripheral::characteristics` in `winrtble` when `discover_characteristics` called. You can get discovered characteristics correctly through `Peripheral::characteristics(&self)` by this workaround.
> Fix updating `Peripheral::characteristics` in `winrtble` (Windows) #170

- src/corebluetooth/adapter.rs
Update peripheral properties in the `CoreBluetoothEvent::DeviceUpdated` event
> Workaround for #172

- src/lib.rs
This seems to work, and would fix #178
> Require boxed error variant to be Send + Sync

- src/winrtble/utils.rs
While experimenting with using btleplug on Windows with heart rate monitors where I was expecting to see characteristics with the notify property I noticed that no characteristics had any properties.
Poking around I saw that the `utils.rs::to_char_props()` utility hadn't been implemented yet and it was just returning blank flags.
After implementing this I can now see properties as expected.
As a side note: I noticed on Windows there are two additional properties documented here: https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.genericattributeprofile.gattcharacteristicproperties?view=winrt-20348
`ReliableWrites` and `WritableAuxiliaries`
I wonder if `CharPropFlags` should be expanded to a u32 as on Windows and these properties could be reported too?
> winrtble: report characteristic properties

- Cargo.toml
- src/winrtble/peripheral.rs
As a follow up to https://github.com/deviceplug/btleplug/issues/182 this updates the winrt backend to use a broadcast channel as the basis for supporting characteristic `notifications()`
The adds a dependency on the `sync` feature of tokio to be able to use `tokio::sync::broadcast`. It also adds a dependency on `tokio-stream` to be able to use `tokio_stream::wrappers::BroadcastStream` for conveniently creating a Stream from a `broadcast` channel.
Overall this avoids the need for a boxed vector of mpsc channels and needing to lazily/manually clean up stale channels.
It should also be trivial to make an equivalent change to the corebluetooth backend but since I'm not able to test that easily myself currently I haven't included that change as part of this PR.
> winrtble: broadcast channel notifications

- src/common/adapter_manager.rs
- src/winrtble/peripheral.rs
_Note: this PR is based on top of https://github.com/deviceplug/btleplug/pull/184 so the first two patches can be ignored_
As another follow up to #182 this makes equivalent changes to the `AdapterManager` to use a broadcast channel for streaming `CentralEvent`s; avoiding the need to track a set of `mpcs` channels and the need to clean up stale senders.
> Central broadcast channel events

- src/common/adapter_manager.rs
- src/common/util.rs
- src/corebluetooth/peripheral.rs
- src/winrtble/peripheral.rs
_Note: this PR is based on https://github.com/deviceplug/btleplug/pull/185 so the first three patches can be ignored_
This (blindly) makes the same change as made in https://github.com/deviceplug/btleplug/pull/183 and https://github.com/deviceplug/btleplug/pull/184 for the corebluetooth backend. (untested)
Since the corebluetooth and winrt backend would now follow a common pattern, this also factors out a `notifications_stream_from_broadcast_receiver()` utility for making a ValueNotification event Stream from a Broadcast receiver.
> Corebluetooth broadcast notifications

- CHANGELOG.md
- src/api/mod.rs
- src/common/adapter_manager.rs
- src/corebluetooth/adapter.rs
- src/corebluetooth/internal.rs
`CentralEvent::DeviceLost` was never constructed anywhere. `CoreBluetoothEvent::DeviceLost` actually corresponds to `CentralEvent::DeviceDisconnected`, so rename it to match.
Fixes #176.
> Remove CentralEvent::DeviceLost and rename CoreBluetoothEvent::DeviceLost

- src/common/adapter_manager.rs
- src/corebluetooth/adapter.rs
- src/corebluetooth/internal.rs
Fix some warnings and name `CoreBluetoothEvent` enum variant fields.
> Minor cleanups for CoreBluetooth implementation

- examples/discover_adapters_peripherals.rs
- examples/lights.rs
- examples/subscribe_notify_characteristic.rs
- src/api/mod.rs
- src/bluez/peripheral.rs
- src/corebluetooth/central_delegate.rs
- src/corebluetooth/framework.rs
- src/corebluetooth/internal.rs
- src/corebluetooth/peripheral.rs
- src/lib.rs
- src/winrtble/ble/characteristic.rs
- src/winrtble/ble/device.rs
- src/winrtble/ble/mod.rs
- src/winrtble/ble/service.rs
- src/winrtble/peripheral.rs
Rather than lumping all characteristics together, we should group them by service.
This fixes #11.
> Group characteristics by service

- examples/event_driven_discovery.rs
- src/api/mod.rs
- src/bluez/adapter.rs
- src/bluez/peripheral.rs
- src/common/adapter_manager.rs
- src/corebluetooth/adapter.rs
- src/corebluetooth/peripheral.rs
- src/platform.rs
- src/winrtble/adapter.rs
- src/winrtble/peripheral.rs
As requested by @qwandor in https://github.com/deviceplug/btleplug/pull/204#discussion_r697609014.
I changed the MacOS and Windows platform only as much as necessary, since I don't have a machine to test it.
> Add type PeripheralId 

- examples/subscribe_notify_characteristic.rs
* Add logging.
* Limit the number of notifications printed.
* Handle disconnection errors the same as other errors.
* Only try to discover services if we connected.
> Minor cleanups to example

- src/winrtble/ble/device.rs
- src/winrtble/peripheral.rs
`BLEDevice::connect` used a cache when requesting gatt services.
This means that a connection to the device might not be established if the services were previously cached.
Thus, a peripheral may not always be connected even if `Peripheral::connect` returns `Ok`.
After this change the gatt services are requested without the cache when connecting. `discover_services` may still use the cache.
> winrtble: Cache is no longer used when requesting gatt services in `connect`

- src/common/adapter_manager.rs
- src/corebluetooth/adapter.rs
- src/corebluetooth/peripheral.rs
- src/winrtble/adapter.rs
- src/winrtble/peripheral.rs
AdapterManager and Peripherals had reference counted pointers to each other. This prevented them from ever getting disposed. If a connected peripheral is never disconnected manually, it would stay connected until the process is terminated.
There is now ever only a single instance of AdapterManager and peripherals have a weak reference to it.
Additionally, there was a reference cycle between Peripheral and BLEDevice in winrtble. ConnectedEventHandler in BLEDevice now uses a weak reference.
> Fix reference cycles in peripherals

- examples/discover_adapters_peripherals.rs
- examples/event_driven_discovery.rs
- examples/lights.rs
- examples/subscribe_notify_characteristic.rs
- src/api/mod.rs
- src/bluez/adapter.rs
- src/corebluetooth/adapter.rs
- src/corebluetooth/internal.rs
- src/lib.rs
- src/winrtble/adapter.rs
The [`requestDevice`](https://webbluetoothcg.github.io/web-bluetooth/#dom-bluetooth-requestdevice) method from _WebBluetooth_ requires a list of service uuids to allow access to characteristics. See [the code](https://github.com/deviceplug/btleplug/blob/2cb6cb233dbcacfe9b79ef9ba1289b66ede0e8cb/src/wasm/adapter.rs#L99-L101) of #204 for more details.
> Add ScanFilter to Central::start_scan()

- Cargo.toml
- examples/discover_adapters_peripherals.rs
- src/api/mod.rs
- src/bluez/adapter.rs
- src/corebluetooth/adapter.rs
- src/lib.rs
- src/winrtble/adapter.rs
Implemented on Linux for now, other platforms have placeholders.
First step of #138.
> Add method to get adapter information for debug

- examples/event_driven_discovery.rs
- examples/lights.rs
- src/lib.rs
- src/winrtble/ble/characteristic.rs
- src/winrtble/ble/device.rs
- src/winrtble/manager.rs
- src/winrtble/peripheral.rs
- src/winrtble/utils.rs
Minor thing that AFAICT `events_receiver()` is gone, in favor of `events()`.
This patch just updates places in docs and examples where `events_receiver()` was referred to.
> In docs use events() instead of event_receiver().

- src/corebluetooth/framework.rs
- src/corebluetooth/internal.rs
- src/corebluetooth/utils/core_bluetooth.rs
Initial work on a solution for #224 
Hi,
I'd like to preface this by stating I'm super new to bluetooth, objective-c ffi, rust, and open source. So I'm about as in over my head as it gets. But I had a test environment for this bug and a desire to fix it, so here we are. I figured even if this doesn't end up being a good patch, it's a good test. I've tested this against [this gist](https://gist.github.com/subtle-supernova/495e9f0931b132751f85d2c109486fed) which scan for sennheiser devices and therefor pickup my headphones. My test returned a device id `00:00:00:00:00:00` with the connected bool as `false`, but I'm unsure if that's related to any of the changes I've made here.
Please let me know if there's anything else I can do, and thank you for the library.
> initial work on bluetooth from macos 12.x using filter

- src/corebluetooth/central_delegate.rs
- src/corebluetooth/framework.rs
- src/corebluetooth/internal.rs
- src/corebluetooth/utils/core_bluetooth.rs
- src/corebluetooth/utils/mod.rs
- src/corebluetooth/utils/nsstring.rs
I've removed a few unused functions, used some of the wrappers and types from the `cocoa` crate (seeing as we are depending on it anyway) and some of the helpers we already have. This simplifies some of the code a bit.
> Clean up CoreBluetooth code and use more wrappers from cocoa crate

- CHANGELOG.md
- src/api/bdaddr.rs
- src/bluez/peripheral.rs
- src/corebluetooth/peripheral.rs
- src/platform.rs
- src/winrtble/peripheral.rs
Also ensure that `PeripheralId` implements `Hash` on all platforms.
> Derive Ord for BDAddr and PeripheralId.

- CHANGELOG.md
- Cargo.toml
- src/bluez/adapter.rs
This will be a bit nicer once https://github.com/bluez-rs/bluez-async/pull/20 is in.
Fixes the second issue found while investigating #241.
> Make Central methods on Bluez Adapter only affect that adapter

- Cargo.toml
- src/bluez/adapter.rs
- src/bluez/peripheral.rs
Use `DeviceId` rather than MAC address as `PeripheralId` on Linux.
This is purely an internal cleanup with no API impact.
> Clean up PeripheralId on Linux

- Cargo.toml
The [RUSTSEC-2022-0002](https://rustsec.org/advisories/RUSTSEC-2022-0002.html) advisory identifies a memory vulnerability in version `5.0.0` of the [`dashmap`](https://crates.io/crates/dashmap) crate.
This vulnerability has been resolved in `dashmap 5.1.0`
More information:
* https://github.com/xacrimon/dashmap/issues/167
* https://github.com/xacrimon/dashmap/pull/180
> build: bump `dashmap` version to `5.1.0` and resolve `RUSTSEC-2022-0002`

- Cargo.toml
The [RUSTSEC-2022-0008](https://rustsec.org/advisories/RUSTSEC-2022-0008.html) advisory identifies a data race and undefined behavior vulnerability in version `0.28.0` of the [`windows`](https://crates.io/crates/windows) crate.
This vulnerability has been resolved in `>=  0.32.0`
More information:
* https://github.com/microsoft/windows-rs/issues/1409
> buid: bump `windows` crate version to `0.33.0` to resolve `RUSTSEC-2022-0008`

- CHANGELOG.md
- Cargo.toml
- README.md
- src/corebluetooth/internal.rs
- src/corebluetooth/peripheral.rs
Implementing disconnect for CoreBluetooth. Pretty much just glue code for CB calls that were already in the library.
@qwandor Reviewing mostly as ritual/habit here, can't remember how familiar you are with the CB stuff, so nbd if you aren't up to reviewing it. I've done some cursory testing with this on iOS and it seems happy.
I need this for my upcoming mobile app release so hoping to land/release soon.
> Implement disconnect for CoreBluetooth

- src/bluez/adapter.rs
- src/bluez/peripheral.rs
- src/corebluetooth/adapter.rs
- src/corebluetooth/peripheral.rs
- src/platform.rs
- src/winrtble/peripheral.rs
This lets clients render the `PeripheralId` in some platform-specific way for users to distinguish devices, without exposing the internal representation to the API as #266 proposed to do.
> Implement Display for PeripheralId

- src/corebluetooth/internal.rs
When a device disconnects, the `on_peripheral_disconnect` handler fires, which tries to fulfill a future for an awaiting call to `disconnect_peripheral`.
However, a device may disconnect for reasons other than a call to `disconnect_peripheral`. In this case there is no future to fulfill. This leads a panic when unwrapping `disconnected_future_state` in `confirm_disconnect`.
This appears to be the cause of issues #273, #270 and possibly #271.
This change skips fulfilling the future if there is none, to avoid this panic. (The disconnect notification will still fire.)
This seems to work well in my testing, but I'm not familiar with the architecture of btleplug so this may not be the right approach.
> CoreBluetooth: skip fulfilling disconnect future if not present

- src/winrtble/peripheral.rs
After disconnecting from a peripheral with `device.disconnect()` on Windows, `device.is_connected()` still returned `true`. The disconnect event always happened. Only the state was not reflected correctly.
Tested successfully on Windows 11.
This bug is also mentioned in issue #212.
> Set the "connected" state to false when disconnecting on Windows.

- src/bluez/adapter.rs
Fixes #289
This makes bluez discovery work like it does on macOS and Windows.
> Set `DuplicateData = true` for bluez

- src/corebluetooth/framework.rs
* this fixes compilation of dylib for ios targets since AppKit is only available in macos sdk
> corebluetooth: conditionally link against AppKit framework

- src/winrtble/ble/device.rs
- src/winrtble/peripheral.rs
Fixes #300 
You must explicitly disconnect from each service before disconnecting from the device. Otherwise, Windows does not seem to fully disconnect the device internally.
See https://stackoverflow.com/questions/39599252/windows-ble-uwp-disconnect for similar issues.
I did this by simply adding a list of services to the `BLEDevice` when `discover_services` is called, allowing us to `Close` them when the device is dropped. This appears to work in my use-case, but I'd be interested to see if it's a robust enough solution for other folks.
> Fix disconnect when using the winrt backend.

- src/api/bdaddr.rs
- src/api/mod.rs
- src/bluez/peripheral.rs
- src/common/adapter_manager.rs
- src/common/util.rs
- src/winrtble/ble/characteristic.rs
- src/winrtble/peripheral.rs
- src/winrtble/utils.rs
Running cargo clippy generates a bunch of warnings which this commit resolves for both Windows and Linux:
```
$ cargo clippy
Checking btleplug v0.11.1 (C:\Users\mamad\Desktop\dev\btleplug)
warning: redundant field names in struct initialization
--> src\winrtble\peripheral.rs:93:17
|
93 |                 adapter: adapter,
|                 ^^^^^^^^^^^^^^^^ help: replace it with: `adapter`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_field_names
= note: `#[warn(clippy::redundant_field_names)]` on by default
warning: redundant field names in struct initialization
--> src\winrtble\peripheral.rs:95:17
|
95 |                 address: address,
|                 ^^^^^^^^^^^^^^^^ help: replace it with: `address`
|
= help: for further …
```
> eliminate cargo clippy warnings

- src/winrtble/peripheral.rs
Prior to this commit, the `discover_services` method would return `Ok(())` even if the underlying calls had failed.
This was causing a deadlock on my system when I tried to reconnect to a device that had just been disconnected.
> fix: winrt: Return error when discovering services fails

- CHANGELOG.md
- Cargo.toml
- src/winrtble/ble/device.rs
- src/winrtble/peripheral.rs
This brings the Windows implementation in line with Linux
Fixes #361
> Ignore failed descriptor reads on Windows

- examples/event_driven_discovery.rs
- src/corebluetooth/central_delegate.rs
- src/corebluetooth/internal.rs
- src/corebluetooth/utils/mod.rs
Corebluetooth stack discovers my BTLE device with a very generic name while having a correct name on Windows and on Android.
This PR implements the fix suggested in https://github.com/deviceplug/btleplug/issues/334 and extends the event_driven_discovery example to print peripheral names.
I'm not sure it's the best approach to merge `Advertisement Data[Local Name]` and peripheral names when they're both present, so I'm open for better ideas.
> fix: make local_name in corebluetooth more descriptive

- src/corebluetooth/central_delegate.rs
- src/corebluetooth/internal.rs
Reading out the value of the descriptors was not correctly implemented before. My solution needs to be extended with all the possible standards descriptor UUIDs but it provides a good starting point.
Also fixes a delegate bug (there were incorrect methods assigned to the functions)
> fix(macos): reading descriptor value

- examples/event_driven_discovery.rs
- src/api/mod.rs
- src/bluez/adapter.rs
- src/corebluetooth/adapter.rs
- src/corebluetooth/central_delegate.rs
- src/corebluetooth/internal.rs
- src/droidplug/adapter.rs
- src/winrtble/adapter.rs
- src/winrtble/manager.rs
Hi,
I'm working on bluetooth integration for [trezor-suite](https://github.com/trezor/trezor-suite) app and i would like to use `btleplug` as a bridge between the electron app and bluetooth device.
To make it work i would like to contribute and address some missing features and issues
Implementation of https://github.com/deviceplug/btleplug/issues/280 for macos, windows and linux.
I wasn't sure should i extend existing `adapter_info` method or just add new `adapter_state`, just for clarity i've added new function. I'm leaving this decision to you.
Also i'm not sure about the naming `adapter_state() -> CentralState` i didn't want to mess up current naming convention.
Feel free to nitpick anything.
Tested on Windows 10, macOS sonoma, linux nixOS
- c244d4170b93fa904bf67d0848926058284cdd30 …
> Feat: CentralState

- .github/workflows/rust.yml
- Cargo.toml
Android is currently broken in dev due to a change in the jni crate that's not supported by jni_utils. This was undetected due to lack of CI.
> build: Add Android CI and fix jni/jni_utils version

- src/api/bdaddr.rs
ran into this while trying to use `DBAddr` as a value in a toml map.
Trying to deserialize a toml like
```toml
"00:11:22:33:44:55" = "Test"
```
into a `HashMap<BDAddr, String>`
results in the error
```
Error: TOML parse error at line 5, column 1
|
5 | "00:11:22:33:44:55" = "Test"
| ^^^^^^^^^^^^^^^^^^^
invalid type: string "00:11:22:33:44:55", expected A colon seperated Bluetooth address, like `00:11:22:33:44:55`
```
By making the `Visitor` also handle owned and ephemeral strings the deserialization works as expected.
> fix: allow deserializing BDAddr from non-borrowed strings

- src/corebluetooth/internal.rs
- src/corebluetooth/peripheral.rs
Fixing `corebluetooth` pending subscription features.
Im trying to connect to a peripheral which requires number comparison pairing.
To enforce pairing process i need to call subscribe, read or write on protected characteristic, this will open native system window and display numbers to compare.
If everything goes well then i receive OK on the subscription.
However if i cancel the system number comparison or disconnect the device during that process i will get `DeviceDisconnected` event but those pending subscription requests are never resolved.
With this fix they should be fulfilled with "Device disconnected" error
> fix: `corebluetooth` fulfill characteristics futures on peripheral disconnection

- Cargo.toml
- src/api/bdaddr.rs
There was a problem with deserialization when using [toml](https://crates.io/crates/toml) crates, so I fixed it.
I often use toml files to configure my own software, but the following deserialization using toml was failing.
```rust
#[derive(Deserialize, PartialEq, Copy, Clone, Debug)]
struct Data {
addr: BDAddr,
}
toml::from_str(r#"addr = "ff00ff00ff00""#) // error: A colon seperated Bluetooth address, like `00:11:22:33:44:55`
```
> Deserializing BDAddr from non-borrowed string without clone

- src/bluez/peripheral.rs
- src/corebluetooth/internal.rs
- src/droidplug/peripheral.rs
- src/winrtble/peripheral.rs
If a device (like the LOOB) declares multiple characteristics on a service with the same UUID, the last declared characteristic is used not the first (which is what the LOOB requires us to control).
Ideally we'd have access to them all, but since we can't tell them apart at the higher levels first wins seems better than last wins.
This has been tested on Windows, macOS, Android and Linux
> fix: Duplicate Characteristic UUID overwrite each other

- src/droidplug/java/src/main/java/com/nonpolynomial/btleplug/android/impl/Adapter.java
- src/droidplug/java/src/main/java/com/nonpolynomial/btleplug/android/impl/Peripheral.java
This PR adds support for Extended Advertisements from Bluetooth 5.0 on Android.
When creating the `ScanSettings` object by default only Legacy Advertisements are reported to the ScanCallback. From API Level 26 (Oreo) the developer has the option to also include Extended Advertisements to the reported ScanResults.
Furthermore it is fixing a build issue in the Peripheral.java file where the wrong API call to `BluetoothAdapter` is getting called and I updated it here as well. If necessary I can also do this in a separate PR.
> Added support for Extended Advertisements for Android

- Cargo.toml
The next version of the `objc2` framework crates will have a bunch of default features enabled, see https://github.com/madsmtm/objc2/issues/627, so this PR pre-emptively disables them, so that your compile times down blow up once you upgrade to the next version (which is yet to be released, but will be soon).
> Prepare for `objc2` frameworks v0.3

- Cargo.toml
- examples/discover_adapters_peripherals.rs
- examples/event_driven_discovery.rs
- examples/lights.rs
- examples/subscribe_notify_characteristic.rs
- src/bluez/peripheral.rs
- src/corebluetooth/peripheral.rs
- src/droidplug/peripheral.rs
- src/lib.rs
- src/winrtble/adapter.rs
- src/winrtble/ble/characteristic.rs
- src/winrtble/ble/descriptor.rs
- src/winrtble/ble/device.rs
- src/winrtble/ble/watcher.rs
- src/winrtble/manager.rs
1. update `windows` to 0.61 and fix;
2. add `anyhow` and update `rand` for example;
3. add [`PoisonError`] to [`Error`] for replace `unwrap` to `map_err`;
> Update windows to 0.61
